#!/usr/bin/env bash

BUILD_HASH=${GITHUB_SHA:-unknown}
BUILD_TIME_UNIX=$(date +%s)
BUILD_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

if [ -z "$INPUT_RELEASE_VERSION" ]; then
  TAGS_PREFIX=refs/tags/
  if [[ $GITHUB_REF = $TAGS_PREFIX* ]]; then
    INPUT_RELEASE_VERSION=${GITHUB_REF#$TAGS_PREFIX}
  elif [ -n "$GITHUB_RUN_NUMBER" ]; then
    INPUT_RELEASE_VERSION=v$GITHUB_RUN_NUMBER
  else
    INPUT_RELEASE_VERSION=unknown
  fi
fi

ldflags=(
  "-X github.com/daaku/buildinfo.buildHash=$BUILD_HASH"
  "-X github.com/daaku/buildinfo.buildTimeUnix=$BUILD_TIME_UNIX"
  "-X github.com/daaku/buildinfo.buildURL=$BUILD_URL"
  "-X github.com/daaku/buildinfo.releaseVersion=$INPUT_RELEASE_VERSION"
)

IFS=' ' eval 'joined_ldflags="${ldflags[*]}"'
echo "BI_LDFLAGS=$joined_ldflags" >>$GITHUB_ENV
