name: 'go-buildinfo'
description: 'Helps populate buildinfo for Go.'
author: 'Naitik Shah'
inputs:
  release_version:
    description: 'Specify release version to use. Automatically determined if unset.'
runs:
  using: composite
  steps:
    - run: echo "INPUT_RELEASE_VERSION=${{ inputs.release_version }}" >> $GITHUB_ENV
      shell: bash
    - run: ${{ github.action_path }}/action
      shell: bash
