name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release_version:
        description: Custom release version.
        required: false
        default: ""
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - uses: actions/checkout@v3
    - uses: ./
      with:
        release_version: ${{ github.event.inputs.release_version }}
    - name: Env
      run: echo $BI_LDFLAGS
    - name: Build
      run: go build -ldflags="$BI_LDFLAGS" -trimpath
    - name: Execute
      run: ./go-buildinfo
